version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskmanager
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5
    ports:
      - '27017:27017'

  redis:
    image: redis:7
    ports:
      - '6379:6379'
